# Use the official PostgreSQL image
FROM postgres:latest

# Set environment variables (change these as needed)
ENV POSTGRES_USER="postgres"
ENV POSTGRES_PASSWORD="postgres"
ENV POSTGRES_DB="webmining"

# Expose PostgreSQL port
EXPOSE 5432
